x-default-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "10"

services:
  web:
    build: ./apps/web
    container_name: dsl-hub-web
    env_file:
      - .env
      - .env.local
    volumes:
      - ./apps/web:/app/web
      - /app/web/node_modules
    environment:
      - MODE=dev
      - PUBLIC_DEV_HOST=localhost      # або твій ngrok-домен
      - VITE_HMR_USE_WSS=false         # true, якщо відкриваєш по https
      - WATCH_POLL=1
    command: sh -c "npm ci --include=dev && npm run dev -- --host --port ${WEB_PORT}"
    ports:
      - "${WEB_PORT:-3000}:${WEB_PORT:-3000}"
    restart: unless-stopped
    logging: *default-logging
#    depends_on:
#      - agent

#  agent:
#    build:
#      context: ./apps/agent
#      dockerfile: Dockerfile
#    container_name: dsl-hub-agent
#    ports:
#      - "${AGENT_PORT:-5000}:5000"
#    env_file:
#      - .env
#      - .env.local
#    environment:
#      - PYTHONUNBUFFERED=1
#    volumes:
#      - ./apps/agent:/app
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 20s
#    logging: *default-logging
