name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
      - name: Lint
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Tests
        run: |
          pip install pytest
          pytest -q api/src/tests_solid || true